### ISSUE TITLE
animations frame drops

### ISSUE THREAD

**Issue by etechwall** [SuperXOS/superx-store#32]

**Comment by wrix** [comment]
Only software-based rendering is enabled right now as otherwise the app store crashes (Chromium backend crashes) on NVidia cards, the issue is with the driver from what I understand. We will see if the system is NOT using NVidia and enable hardware acceleration which should bring back the framerates.

This needs more testing on different GPUs before we finalize what acceleration to use on what systems.

**Comment by wrix** [comment]
Implemented checking of GPU driver and use software OpenGL selectively. Fix in 49896c26ab32822af74be7dc7c82189e1d1cc6d4
